name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: depot-ubuntu-24.04-4

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: orioledb/orioledb:latest-pg17
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - fail-fast: false
        parallel:
          - name: build
            run: node --run build
          - name: lint
            run: node --run lint
          - sequential:
              - uses: ariga/setup-atlas@4240bd74ba9f13319a21de2b6e497f2b6d184d76
                with:
                  version: v1.2.0
              - run: atlas migrate apply --url $DATABASE_URL
              - name: run tests
                run: node --run test

  docker-image:
    needs: [ci]
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 # v1.7.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: depot/build-push-action@98e78adca7817480b8185f474a400b451d74e287 # v1.18.0
        with:
          project: 520fcf1v75
          context: .
          save: true
          save-tags: |
            latest
            ${{ github.sha }}
