name: CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/CICD.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/CICD.yml"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --immutable

      - uses: actions/upload-artifact@master
        with:
          name: dependencies
          path: ./node_modules

  lint:
    runs-on: ubuntu-latest

    needs:
      - dependencies

    steps:
      - name: download webapp artifacts
        uses: actions/download-artifact@master
        with:
          name: dependencies
          path: ./node_modules

      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest

    needs:
      - dependencies

    steps:
      - name: download webapp artifacts
        uses: actions/download-artifact@master
        with:
          name: dependencies
          path: ./

      - run: yarn typecheck
